services:
  redis-examples-redis-data:
    container_name: redis-container
    image: redis:7
    ports:
      - "16379:6379"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    volumes:
      - redis-data:/data

volumes:
  redis-data: