spring:
  application:
    name: redis-examples

  datasource:
    url: jdbc:h2:mem:redis-example-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:16379}
      password: ${REDIS_PASSWORD:pass}
      database: 0
      timeout: 5000  # (ms)
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 5000ms
        shutdown-timeout: 100ms
        client-options:
          auto-reconnect: true
          cancel-commands-on-reconnect-failure: true
      ssl:
        enabled: false

logging:
  level:
    org.apache.commons.pool2: DEBUG
    io.lettuce.core.resource: DEBUG